Preparing for booster 0.6.0 release
quartiq/booster pull request #436
Opened 2024-08-28 15:28 UTC by ryan-summers

This PR preps for a 0.6.0 release.

2024-08-28 15:31 UTC, jordens commented
https://github.com/quartiq/booster/blob/cab97464f4e34e862371bb2fa25784dddfdc79a7/Cargo.toml#L67 needs to go first

2024-08-28 15:56 UTC, jordens commented
And I guess some/many of the included crates in booster also need a bump (assuming they have changed, for e.g. the e-h 1 port).

2024-08-29 07:59 UTC, jordens commented on CHANGELOG.md
> +None yet!
Only add this section after release.

2024-08-29 10:36 UTC, ryan-summers commented
@jordens There's also the `debounced-pin` and `minireq` crates. We can publish an updated minireq, but `debounced-pin` isn't owned by us. We could:
1. Republish rust-debounced-pin (and maybe move it over to the Rust-embedded-community)
2. Move the implementation for debouncing directly into `booster` (it's not complex)
3. Find an alternative crate

Ay particular preference here?

2024-08-29 15:10 UTC, jordens reviewed
No releases for the `ad5627` etc. crates?

2024-08-29 15:16 UTC, ryan-summers commented
They all have their versions already bumped. I ran through about 30 minutes ago and released them all as 0.2 already.

2024-08-29 15:21 UTC, jordens approved these changes

2024-08-29 15:27 UTC, jordens requested changes
> warning: package `cortex-m-rt v0.7.4` in Cargo.lock is yanked in registry `crates-io`, consider updating to a version that is not yanked

2024-08-29 15:55 UTC, jordens approved these changes

2024-08-29 16:02 UTC, merged